### ISSUE TITLE
panic: open /home/ubuntu/Documents/googleplay.txt: no such file or directory

### ISSUE THREAD

**Issue by shifoc** [4cq2/googleplay#10]
I did `googleplay -email EMAIL -passwd PASSWORD` and got 
```
POST https://android.googleapis.com/auth
panic: open /home/ubuntu/Documents/googleplay.txt: no such file or directory

goroutine 1 [running]:
main.main()
        /home/ubuntu/googleplay/cmd/googleplay/main.go:47 +0x605
```

**Comment by 4cq2** [comment]
can you please give the output of `ls /home/ubuntu`

**Comment by shifoc** [comment]
go googleplay

**Comment by 4cq2** [comment]
`/home/ubuntu/Documents` should exist:

https://askubuntu.com/questions/1064544/how-are-the-default-user-folders-in-the-home-created-for-a-new-user

can you explain how you installed Ubuntu?

**Comment by shifoc** [comment]
EC2 instance with ubuntu installed

**Comment by shifoc** [comment]
I created the folder Documents and it seems to have worked

**Comment by 4cq2** [comment]
OK this should be fixed now:

https://github.com/4cq2/googleplay/blob/24a5af5be8b17be61292053392fc112984f2a052/cmd/googleplay/main.go#L39-L44

any cache or configuration files will be under this folder going forward

**Comment by 4cq2** [comment]
note its here now:

https://github.com/4cq2/googleplay/blob/1e1549e77a74e704d006e00a1df332b424a397fc/cmd/googleplay/main.go#L39-L43

to account for my other projects - hopefully this is the last change
