### ISSUE TITLE
Search Keywords Feature

### ISSUE THREAD

**Issue by EgorSigolaev** [4cq2/googleplay#14]
Hello! The library works great. I have one question. Would it be hard to add a search method to make an install by selected search phrase? If it's possible, I will definitely donate and support project.

**Comment by 4cq2** [comment]
can you give an example input and expected output?

**Comment by EgorSigolaev** [comment]
> can you give an example input and expected output?

Actually I don't completely understand how it works in details with api. But I can provide users flow.
1)Launch Play Market
2)Input search request in the search bar. For example "Music player".
3)Find required app (by package name or something else)
4)Download it (purchase).

I think when you navigate and download app from search list, Play Market puts search query as request param. Because a simple install and an install from search list using keywords are completely different.

**Comment by 4cq2** [comment]
OK I am not interested in that issue, but I can implement it for a fee. if you want to send me an offer I will consider it:

https://github.com/4cq2/googleplay#contact

or you can give me your contact info and I can send a price.

**Comment by EgorSigolaev** [comment]
> OK I am not interested in that issue, but I can implement it for a fee. if you want to send me an offer I will consider it:
> 
> https://github.com/4cq2/googleplay#contact
> 
> or you can give me your contact info and I can send a price.

Ok. I've sent you request in discord.
