### ISSUE TITLE
ARMv6 architecture

### ISSUE THREAD

**Issue by NicknineTheEagle** [4cq2/googleplay#5]
There are some really old apps that are ARMv6 only (e.g. com.gameloft.android.ANMP.GloftAsphalt5.asphalt5), any idea how to fetch them? I tried to setting "armeabi" as the platform name but that doesn't seem to be it as it's still saying that the device is incompatible.
```
>googleplay.exe -d com.gameloft.android.ANMP.GloftAsphalt5.asphalt5 -p 3
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.gameloft.android.ANMP.GloftAsphalt5.asphalt5
panic: your device isn't compatible with this version
```
3 is the custom "armeabi" platform I've added locally.

**Comment by 4cq2** [comment]
I dont offer free support for any APK older than one year. So you if you can present evidence of a recent APK using this platform, then I will consider it. Or if you want to purchase paid support, contact me:

https://github.com/4cq2/googleplay#contact

otherwise, good luck.
