### ISSUE TITLE
Cannot login. 403

### ISSUE THREAD

**Issue by iambenmitchell** [4cq2/googleplay#6]
Getting this error when trying to sign in:

```
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
        /root/googleplay/cmd/googleplay/main.go:45 +0x5e5
```

**Comment by 4cq2** [comment]
please provide example command

**Comment by iambenmitchell** [comment]
`root@python-4235-cb0c2d:~/googleplay/cmd/googleplay# ./googleplay --email "email@domain.com" --passwd "password"`

OUTPUT:

```
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
        /root/googleplay/cmd/googleplay/main.go:45 +0x5e5
root@python-4235-cb0c2d:~/googleplay/cmd/googleplay# 
```

**Comment by 4cq2** [comment]
If your password has strange characters, your shell could be fucking up the input. I would recommend put the password in a file, then try:

~~~
googleplay -email email@domain.com -f password.txt
~~~

**Comment by iambenmitchell** [comment]
My password only has an @ at the end to meet the requirements.

I put it in a file and tried again, same error.

```
root@python-4235-cb0c2d:~/googleplay/cmd/googleplay# ./googleplay --email "email@email.com" -f pass.txt 
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
        /root/googleplay/cmd/googleplay/main.go:45 +0x5e5
```

**Comment by 4cq2** [comment]
I normally do not provide free support, because people have repeatedly abused it. see https://github.com/4cq2/googleplay/pull/4 as just one of many, many examples over the years. However I did want to mention the `-f` option because it is new. If you wish to purchase paid support, contact me:

https://github.com/4cq2/googleplay#contact

otherwise good luck.
