### ISSUE TITLE
404 error for auth url

### ISSUE THREAD

**Issue by garikello3d** [4cq2/googleplay#7]
Downloaded the fresh source, built and tried to use.

```
$ ./googleplay -email mygoogleemail -passwd mygooglepassword
POST https://android.googleapis.com/auth
panic: 404 Not Found

goroutine 1 [running]:
main.main()
	/home/user/googleplay/cmd/googleplay/main.go:45 +0x5e5
```

**Comment by 4cq2** [comment]
if your password has any special characters, your shell might be fucking up the input. if thats the case, put the raw password into a file, and try again:

~~~
googleplay -email mygoogleemail -f password.txt
~~~

**Comment by garikello3d** [comment]
My password is a pure English word, no shell pitfalls is possible. So the question remains. Actually this URL [https://android.googleapis.com/auth](https://android.googleapis.com/auth) really gives 404, so the program's complain is technically correct.

**Comment by 4cq2** [comment]
sorry, you've reached the end of the free support. if you wish to purchase paid support, contact me:

https://github.com/4cq2/googleplay#contact

otherwise good luck.
