### ISSUE TITLE
Purchase Required

### ISSUE THREAD

**Issue by Neuromantestd** [4cq2/googleplay#8]
There is a lot of free applications that say to require purchase when trying to download them.
I execute the purchase command but nothing changes.
One example of this is com.fingersoft.hcr2
I don't know why this could happen and the device doesn't seem to fix it.

**Comment by 4cq2** [comment]
I just tested this and everything works as it should. If you are interested in paid support, contact me:

https://github.com/4cq2/googleplay#contact

otherwise good luck.
